# Generated by Django 2.0.3 on 2018-05-04 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180504_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='name',
        ),
    ]
