# Generated by Django 2.0.3 on 2018-03-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_uploadfilemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='UploadFileModel',
        ),
    ]
